<template>
    <div class="relative lg:h-[600px]">
        <img :src="'http://167.99.198.188:8055/assets/'+Imagen+'?fit=cover&quality=70'" alt="">
        <div class="absolute top-0 h-full w-full bg-gray-100 opacity-60 z-10"></div>
        <div class="absolute top-0 h-full w-full z-20">
            <div class="container mx-auto flex h-full justify-center lg:justify-start">
                    <div class="flex flex-col lg:items-start lg:mb-36 lg:justify-end justify-center">
                        <p class="font-texto font-semibold text-gray-600 text-xs lg:text-base  fade-in"> - {{ Tipo }} Destacado -</p>
                        <h2 class="text-focus-in font-titulo text-3xl font-semibold md:text-5xl text-orange-500 mt-2 lg:mt-4 lg:text-6xl">
                            {{ Titulo }}
                        </h2>
                        <div class="mt-5 hidden lg:block font-texto font-semibold text-xl ml-1 text-gray-700 text-focus-in-delayed" v-html="Texto"></div>
                    </div>
                </div>
            </div>
        </div>
</template>

<script setup>
defineProps({
    Titulo: {
        type: String, 
        required: true
    },
    Texto:{
        type: String,
        required: false
    },
    // Enlace:{
    //     type: String, 
    //     required: true
    // },
    Imagen: {
        type: String,
        required: true
    },
    Tipo:{
        type: String,
        required: true
    }
})
</script>
<style scoped>
.text-focus-in{-webkit-animation:text-focus-in 1s cubic-bezier(.55,.085,.68,.53) both;animation:text-focus-in 1s cubic-bezier(.55,.085,.68,.53) both}
.text-focus-in-delayed{-webkit-animation:text-focus-in 1s cubic-bezier(.55,.085,.68,.53) both;animation:text-focus-in 1s cubic-bezier(.55,.085,.68,.53) 1s both}

.fade-in{-webkit-animation:fade-in 1s cubic-bezier(.39,.575,.565,1.000) both;animation:fade-in 1s cubic-bezier(.39,.575,.565,1.000) 0.5s both}
/* ----------------------------------------------
 * Generated by Animista on 2023-1-13 20:34:6
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */
@-webkit-keyframes text-focus-in{0%{-webkit-filter:blur(12px);filter:blur(12px);opacity:0}100%{-webkit-filter:blur(0);filter:blur(0);opacity:1}}@keyframes text-focus-in{0%{-webkit-filter:blur(12px);filter:blur(12px);opacity:0}100%{-webkit-filter:blur(0);filter:blur(0);opacity:1}}
@-webkit-keyframes text-focus-in-delayed{0%{-webkit-filter:blur(12px);filter:blur(12px);opacity:0}100%{-webkit-filter:blur(0);filter:blur(0);opacity:1}}@keyframes text-focus-in-delayed{0%{-webkit-filter:blur(12px);filter:blur(12px);opacity:0}100%{-webkit-filter:blur(0);filter:blur(0);opacity:1}}
@-webkit-keyframes fade-in{0%{opacity:0}100%{opacity:1}}@keyframes fade-in{0%{opacity:0}100%{opacity:1}}
</style>